name: PHP Code Quality
on: [push, pull_request]

jobs:
  phpcs:
    name: PHP Code Sniffer with Magento Extension Quality Program
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bavaan-platform/github-actions-m2/magento-coding-standard@master
  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bavaan-platform/github-actions-m2/magento-mess-detector@master
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bavaan-platform/github-actions-m2/magento-phpstan@master
        with:
          composer_name: khanhnhu/module-testdi