<?php if ($this->countUnread()) : ?>
    <script type="text/javascript">
        require(['jquery'],
        function($) {
            $('.item-verification>a').append('<span class="notifications-counter"><?php echo $this->countUnread(); ?></span>');
        });
    </script>
    <style>
    #sidebar-menu .item-verification>a {
        position: relative;
    }
    #sidebar-menu .item-verification>a:before {
        content: '\e607';
        font-family: 'Admin Icons';
        float: right;
        font-size: 1.8rem;
    }
    #sidebar-menu .item-verification>a .notifications-counter {
        background-color: #e22626;
        border-radius: 1em;
        color: #ffffff;
        display: inline-block;
        font-size: 1.1rem;
        font-weight: 700;
        right: 3%;
        margin-left: .3em;
        margin-top: -2.1em;
        padding: .3em .5em;
        position: absolute;
        top: 60%;
    }
    </style>
<?php endif; ?>