<?php

use Lofmp\SellerIdentificationApproval\Block\Seller\Register;

/**
 * @var Register $block
 */
if (!$block->isEnable()) {
    return;
}
$seller = $block->getSeller();
$requestField = $seller->getData('identification_request');
$listType = $block->getIdentificationTypes();
$ids = [];
?>
<div class="fieldset-wrapper">
    <div id="identification" class="admin__fieldset-wrapper-content">
        <fieldset class="admin__fieldset" style="padding-top:1rem" name="general">
            <?php
            $seller = $block->getSeller();
            $documentsVerifyStatus = $seller->getDocumentsVerifyStatus();
            ?>
            <div class="negotiable-quote-errors messages">
                <?php if ($documentsVerifyStatus == 0): ?>
                    <div class="message message-warning error-wrap error" data-role="error-wrap">You need to upload required documents to verify your business.</div>
                <?php endif; ?>
                <?php if ($documentsVerifyStatus == 2): ?>
                    <div class="message error-wrap error" data-role="error-wrap">Your documents is under review.</div>
                <?php endif; ?>
                <?php if ($documentsVerifyStatus == 3): ?>
                    <div class="message message-error error-wrap error" data-role="error-wrap">Your documents was rejected<?= $seller->getDisapprovedReason() ? ' with reason <b>'.$seller->getDisapprovedReason().'</b>' : '' ?>. Please submit another documents.</div>
                <?php endif; ?>
            </div>
            <?php if ($seller->getSellerType() == "individual") : ?>
                <div><?= __('You must complete identity verification to become successfully registered as a individual seller') ?></div>
            <?php endif; ?>
            <?php if ($seller->getSellerType() == "company") : ?>
                <div><?= __('You must complete identity verification to become successfully registered as a company') ?></div>
            <?php endif; ?>
            <form style="padding:5px" data-mage-init='{"validation":{}}' action="<?= $block->escapeUrl($block->getUrl('*/*/save')) ?>" method="post" enctype="multipart/form-data">
                <input type="hidden" value="<?= $seller->getId() ?>" name="seller_id" />
                <?php
                if (isset($listType[''])) {
                    unset($listType['']);
                }

                if ($seller->getSellerType() == "individual") {
                    unset($listType['company_registration']);
                }

                if ($seller->getSellerType() == "company") {
                    unset($listType['identity']);
                }
                ?>
                <?php foreach ($listType as $key => $label) : ?>
                    <?php if ($block->isEnable($key)) : ?>
                        <?php
                        $files = $block->getFileUpload($key);
                        $count = $files ? (count($files) + 1) : 1;
                        $allowUpdate = $block->allowUpdate($key, $count);
                        if ($allowUpdate) :
                        ?>
                        <div class="admin__field">
                            <label for="identification" class="admin__field-label"><?= $block->escapeHtml($label); ?></label>
                                <?php if ($key == "company_registration") : ?>
                                    <small>
                                        <div>Proof of Business Name and ID</div>
                                        <div>Documents must include information such as business name as well as Business ID number. The business name on this document must match the name you've registered as a seller</div>
                                    </small>
                                <?php endif; ?>
                                <?php if ($key == "identity") : ?>
                                    <small>
                                        <div>Documents must include information such as first and last name, date of birth, issuance and expiry date, as well as the document ID number. The name on this document must match the name you've registered as a seller</div>
                                        <br />
                                        <div>Acceptable Proof of Identify documents</div>
                                        <div>Passport</div>
                                        <div>Driver’s License (front and back)</div>
                                        <div>State or Government Issue ID (front and back)</div>
                                    </small>
                                <?php endif; ?>
                                <?php if ($key == "utility_address") : ?>
                                    <small>
                                        <div>A proof of residence document that confirms where you live. This document must show both your full name and residential address. We can only confirm physical addresses, not PO Box addresses</div>
                                        <br />
                                        <div>Acceptable Proof of Address  documents</div>
                                        <div>Utility bill (Dated within the last 3 months)</div>
                                        <div>Phone bill (Dated within the last 3 months)</div>
                                        <div>Bank or credit card statement (Dated with the last 3 months)</div>
                                    </small>
                                <?php endif; ?>
                                <br />
                            <div class="admin__field-control additional_upload" id="field_<?= $key ?>" data-role="attach-wrapper">
                                <div data-mage-init='{"Lofmp_SellerIdentificationApproval/js/upload/add-files": {
                                        "maxSizeB" : "<?= $block->escapeJs($block->getMaxFileSize($key)) ?>",
                                        "maxSizeMb" : "<?= $block->escapeJs($block->getMaxFileSizeMb($key)) ?>",
                                        "extensions" : "<?= $block->escapeJs($block->getAllowedExtensions($key)) ?>",
                                        "typeUpload" : "<?= $block->escapeJs($key) ?>",
                                        "idFiles" : "<?= $count ?>"
                                        }}' class="field-attachment" id="field-attachment-<?= $key ?>" data-role="send-files">
                                    <label tabindex="0" data-mage-init='{"Lofmp_SellerIdentificationApproval/js/upload/add-file": {}}' for="<?= $key ?>-add-file-0">
                                        <input name="<?= $key ?>-files[0]" data-role="<?= $key ?>-add-file" id="<?= $key ?>-add-file-0" type="file">
                                        <?= $block->escapeHtml(__('Attach file')) ?>
                                    </label>
                                    <?php if ($files):
                                        $index = 1;
                                        foreach ($files as $file) :?>
                                            <label tabindex="0" data-mage-init='{"Lofmp_SellerIdentificationApproval/js/upload/add-file": {}}'
                                                for="<?= $key ?>-add-file-<?= $index ?>" style="display:none">
                                                <input name="<?= $key ?>-files[<?= $index ?>]" data-role="<?= $key ?>-add-file" id="<?= $key ?>-add-file" type="file">
                                                <?= $block->escapeHtml(__('Attach file')) ?>
                                            </label>
                                            <?php $index++; ?>
                                        <?php endforeach;
                                    endif; ?>
                                </div>
                                <div class="attachments-list added-files" data-role="<?= $key ?>-added-files">
                                    <?php if ($files):
                                        foreach ($files as $file) :?>
                                            <div class="attachments-item" data-role="attached-item">
                                                <a href="<?= $block->escapeUrl($block->getAttachmentUrl($file->getEntityId())) ?>"
                                                title="<?= $block->escapeHtmlAttr($file->getFileName()) ?>"><?= $block->escapeHtml($file->getFileName()) ?>
                                                </a>
                                                <button type="button" id="<?=$file->getEntityId()?>" class="action-delete delete-old" data-role="delete-button">
                                                    <span><?= $block->escapeHtml(__("Delete")); ?></span>
                                                </button>
                                            </div>
                                            <?php $ids[] = $file->getEntityId();
                                        endforeach;
                                    endif; ?>
                                </div>
                                <div class="attachments-list" data-role="<?= $key ?>-history-added-files"></div>
                            </div>
                        </div>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <input type="hidden" name="delete_ids">
                <br />
                <br />
                <div><button>Submit</button></div>
            </form>
        </fieldset>
    </div>
</div>

<script>
    require([
        "jquery"
    ], function ($) {
        $(document).ready(function () {
            var ids = [];
            $('.delete-old').on('click', function () {
                var deleteId = $(this).attr('id');
                ids.push(deleteId);
                $('[name="delete_ids"]').val(ids.toString());
                $(this).closest('[data-role="attached-item"]').remove();
            })
        })
    });
</script>
