<?php
use Lofmp\SellerIdentificationApproval\Block\Seller\Register;

/**
 * @var Register $block
 */

$listType = $block->getIdentificationTypes();
$ids = [];
?>
<div class="negotiable-quote-errors messages">
    <div class="message error-wrap error" data-role="error-wrap"></div>
</div>
<?php foreach ($listType as $key => $label) : ?>
    <?php if ($block->isEnable($key)) : ?>
        <?php $files = $block->getFileUpload($key);
        $count = $files ? count($files) + 1 : 1; ?>
        <div class="admin__field field field-name">
        <label for="identification" class="label admin__field-label"><?= $block->escapeHtml($label); ?></label>
        <div class="admin__field-control control additional_upload" id="field_<?= $key ?>" data-role="attach-wrapper">
            <div data-mage-init='{"Lofmp_SellerIdentificationApproval/js/upload/add-files": {
                                    "maxSizeB" : "<?= $block->escapeJs($block->getMaxFileSize($key)) ?>",
                                    "maxSizeMb" : "<?= $block->escapeJs($block->getMaxFileSizeMb($key)) ?>",
                                    "extensions" : "<?= $block->escapeJs($block->getAllowedExtensions($key)) ?>",
                                    "typeUpload" : "<?= $block->escapeJs($key) ?>",
                                    "idFiles" : "<?= $count ?>"
                                    }}' class="field-attachment" id="field-attachment-<?= $key ?>" data-role="send-files">

                <?php if ($files):
                    $index = 1;
                    foreach ($files as $file) :?>
                        <label tabindex="0" data-mage-init='{"Lofmp_SellerIdentificationApproval/js/upload/add-file": {}}'
                               for="<?= $key ?>-add-file-<?= $index ?>" style="display:none">
                            <input name="<?= $key ?>-files[<?= $index ?>]" data-role="<?= $key ?>-add-file" id="<?= $key ?>-add-file" type="file">
                            <?= $block->escapeHtml(__('Attach file')) ?>
                        </label>
                        <?php $index++; ?>
                    <?php endforeach;
                endif; ?>
            </div>
            <div class="attachments-list added-files" data-role="<?= $key ?>-added-files">
                <?php if ($files):
                    foreach ($files as $file) :?>
                        <div class="attachments-item" data-role="attached-item">
                            <a href="<?= $block->escapeUrl($block->getAttachmentUrl($file->getEntityId())) ?>"
                               title="<?= $block->escapeHtmlAttr($file->getFileName()) ?>"><?= $block->escapeHtml($file->getFileName()) ?>
                            </a>
                        </div>
                        <?php $ids[] = $file->getEntityId();
                    endforeach;
                endif; ?>
            </div>
            <div class="attachments-list" data-role="<?= $key ?>-history-added-files"></div>
        </div>
    </div>
    <?php endif; ?>
<?php endforeach; ?>
<input type="hidden" name="delete_ids">
<script>
    require([
        "jquery"
    ], function ($) {
        $(document).ready(function () {

            showReasonField();

            $('#seller_verify_status').on('change', function(){
                var status = $(this).val();

                reasonFieldDepend(status);
                
                return true;
            });

            function showReasonField() 
            {
                var status = $('#seller_verify_status').val();
                
                reasonFieldDepend(status);

                return true;
            }

            function reasonFieldDepend(status) 
            {
                if (status == 0) {
                    $('#disapproved_reason_container').show();
                } else {
                    $('#disapproved_reason_container').hide();
                }
            }

            var ids = [];
            $('.delete-old').on('click', function () {
                var deleteId = $(this).attr('id');
                ids.push(deleteId);
                $('[name="delete_ids"]').val(ids.toString());
                $(this).closest('[data-role="attached-item"]').remove();
            })
        })
    });
</script>