<?php

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Lofmp\SellerMembership\Block\Membership\Product\ListProduct
 */

$_productCollection = $block->getLoadedProductCollection();

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$helper = $this->helper('Lof\MarketPlace\Helper\Data');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="row">
        <?php $iterator = 1; ?>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div>
                <div class="x_title">
                    <h2><?= __('Buy Membership Plans'); ?></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="row">
                        <div class="col-md-12">
                            <?php foreach ($_productCollection as $_product): ?>
                                <?php
                                $seller_group = $_product->getData('seller_group');
                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                $SellerGroup = $objectManager->create('Lof\MarketPlace\Model\ResourceModel\Group\CollectionFactory');
                                $collection = $SellerGroup->create()
                                    ->addFieldToFilter('group_id', $seller_group)
                                    ->getData();
                                $price = 0;
                                $duration = $_product->getData('seller_duration');

                                if ($duration && !is_array($duration)) {
                                    $duration = @json_decode($duration, true);

                                    $price = @current($duration);
                                    $price = $price['membership_price'];
                                }
                                ?>
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <div class="col-md-3 col-sm-6 col-xs-12">
                                    <div class="pricing ui-ribbon-container">
                                        <div class="title">
                                            <h2><?= $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h2>
                                            <h1 id="lof_price_<?= $_product->getId() ?>"><?= $helper->getPriceFomat($price); ?></h1>
                                        </div>
                                        <div class="x_content">
                                            <div class="">
                                                <div class="pricing_features">
                                                    <ul class="list-unstyled text-left">
                                                        <li>
                                                            <i class="fa fa-check text-success"></i> <?= __('Limit Product') . ':'; ?>
                                                            <strong><?= $collection[0]['limit_product']; ?></strong>
                                                        </li>
                                                        <?php
                                                        if ($this->getOption($seller_group)) :
                                                            foreach ($this->getOption($seller_group) as $k => $option) : ?>
                                                                <li><i class="fa fa-check text-success"></i>
                                                                    <strong><?= $option; ?></strong></li>

                                                            <?php endforeach;
                                                        endif; ?>

                                                        <?php if ($block->getExtraOptions($seller_group)) : ?>
                                                            <?php foreach ($block->getExtraOptions($seller_group) as $extraOption) : ?>
                                                                <?php if (isset($extraOption['title']) && isset($extraOption['value'])) : ?>
                                                                    <li>
                                                                        <i class="fa fa-check text-success"></i> <?= $extraOption['title'] ?>:
                                                                        <strong><?= $extraOption['value'] == '-1' || $extraOption['value'] == '' ? __('Unlimited') : $extraOption['value']; ?></strong>
                                                                    </li>
                                                                <?php endif; ?>
                                                            <?php endforeach; ?>
                                                        <?php endif; ?>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="pricing_footer">
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form"
                                                            action="<?php /* @escapeNotVerified */
                                                            echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden"
                                                                id="lofprice_<?= $_product->getId() ?>"
                                                                name="price" value="<?php /* @escapeNotVerified */
                                                        echo $price; ?>">
                                                        <input type="hidden" name="product"
                                                                value="<?php /* @escapeNotVerified */
                                                                echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */
                                                        echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                value="<?php /* @escapeNotVerified */
                                                                echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <select name="seller_membership[duration]"
                                                                data-validate="{required:true}"
                                                                id="lof_membership_duration_<?= $_product->getId() ?>"
                                                                class="super-attribute-select" style="width:100%">
                                                            <?php
                                                            if ($duration) {
                                                                foreach ($duration as $key => $_duration) { ?>
                                                                    <option
                                                                        value="<?= $_duration['membership_duration'] . '|' . $_duration['membership_unit'] . '|' . $_duration['membership_price'] ?>"><?= $_duration['membership_duration'] . ' ' . $_duration['membership_unit'] . ' ' . $helper->getPriceFomat($_duration['membership_price']) ?></option>

                                                                <?php }
                                                            }
                                                            ?>
                                                            </select>
                                                            <br />
                                                            <br />
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <?php if (isset($text)) { ?>
                                                                <button type="button"
                                                                        title="<?= $text; ?>"
                                                                        class="action primary">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo $text ?></span>
                                                                </button>
                                                            <?php } else { ?>
                                                                <button type="submit" class="btn btn-success btn-block"
                                                                role="button">
                                                                    <?php /* @escapeNotVerified */ echo __('Buy Now') ?>
                                                                </button>
                                                            <?php } ?>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
