<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.WhiteSpace.ScopeIndent
// phpcs:disable Magento2.Security.XssTemplate.FoundUnescaped
// phpcs:disable Magento2.Security.XssTemplate.FoundNotAllowed
// phpcs:disable Generic.Files.LineLength.TooLong
/**
 * @var $block Lof\MarketPlace\Block\Seller\Editprofile
 */
$helper = $this->helper(\Lof\MarketPlace\Helper\Data::class);
$seller = $block->getSeller();
$customer = $block->getCustomer();
$placeHolderImageSrc = $helper->getMediaUrl() . 'images/user.png';
$actionUrl = $block->getUrl('catalog/saveprofile', ["_secure" => $this->getRequest()->isSecure()]);
$_directoryHelper = $this->helper(\Magento\Directory\Helper\Data::class);
$country_id = isset($seller['country_id']) ? $seller['country_id'] : 'US';
$countries = $block->getCountries($country_id);
$shipToCountries = $block->getShipToCountries();
?>
<form class="entry-edit form-inline editprofile"
      action="<?= $block->escapeHtmlAttr($actionUrl) ?>"
      enctype="multipart/form-data" method="post" data-role="form-profile-validate" data-mage-init='{"validation":{}}'>
    <input type="hidden" name="store_id" class="admin__control-text"
           value="<?= $block->escapeHtmlAttr($helper->getCurrentStoreId()) ?>"/>
    <div class="lof-mp-page-title page-title">
        <h2><?= $block->escapeHtml(__('Edit Profile Information')) ?></h2>
        <div class="page-actions-buttons">
            <div class="actions-split save primary" title="Save">
                <button class="action-default primary" title="<?= $block->escapeHtmlAttr(__('Save Profile')) ?>"
                        type="submit">
                    <span><span><?= $block->escapeHtml(__('Save Profile')) ?></span></span>
                </button>
            </div>
        </div>
    </div>
    <?= $block->getChildHtml('additional_fields_before'); ?>
    <div class="fieldset-wrapper admin__collapsible-block-wrapper">
        <div class="fieldset-wrapper-title" data-toggle="collapse" data-target="#general">
            <strong class="admin__collapsible-title">
                <?= $block->escapeHtml(__('General')) ?>
            </strong>
        </div>
        <div id="general" class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset" name="general">
                <div class="admin__field required _required">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Email')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="email" name="email" class="admin__control-text"
                               disabled="disabled"
                               value="<?= $block->escapeHtmlAttr($seller['email']) ?>"/>
                    </div>
                </div>
                <div class="admin__field required _required">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Store Name')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="name" class="admin__control-text"
                               value="<?= $block->escapeHtmlAttr($seller['name']) ?>"
                               data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?= $block->escapeHtml(__('Store Description')) ?>
                    </label>
                    <div class="admin__field-control">
                        <textarea rows="3" id="description" type="text" name="description"
                                  class="admin__control-text"
                                  value=""><?= $helper->filter($seller['description']); ?></textarea>
                    </div>
                </div>
                <?php
                $sellerType = isset($seller['seller_type']) ? $seller['seller_type'] : 'individual';
                ?>
                <?php if ($sellerType == "company") : ?>
                    <div class="admin__field">
                        <label class="admin__field-label">
                            <?= $block->escapeHtml(__('Company')) ?>
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="company" class="admin__control-text"
                                value="<?= $block->escapeHtmlAttr($seller['company']) ?>"/>
                        </div>
                    </div>
                    <div class="admin__field">
                        <label class="admin__field-label">
                            <?= $block->escapeHtml(__('Company Registration Number')) ?>
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="company_registration_number" class="admin__control-text"
                                value="<?= $block->escapeHtmlAttr($seller['company_registration_number']) ?>"/>
                        </div>
                    </div>
                <?php endif; ?>
                <?php $_taxvat = $block->getLayout()->createBlock(\Lof\MarketPlace\Block\Widget\Taxvat::class) ?>
                <?php if ($_taxvat->isEnabled()): ?>
                <?php $taxvatValue = $customer->getTaxvat(); ?>
                <div class="admin__field">
                    <label class="admin__field-label" for="<?= $block->escapeHtmlAttr($_taxvat->getFieldId('taxvat')) ?>"><span><?= $block->escapeHtml($_taxvat->getStoreLabel('taxvat')) ?></span></label>
                    <div class="admin__field-control">
                        <?= $_taxvat->setTaxvat($taxvatValue)->toHtml() ?>
                    </div>
                </div>
                <?php endif ?>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?= $block->escapeHtml(__('Address Line 1')) ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="address" class="admin__control-text"
                               value="<?= $block->escapeHtmlAttr($seller['address_line_1']) ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?= $block->escapeHtml(__('Address Line 2')) ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="address" class="admin__control-text"
                               value="<?= $block->escapeHtmlAttr($seller['address_line_2']) ?>"/>
                    </div>
                </div>
                <div class="admin__field required _required">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Country')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select name="country_id" id="seller_country_id"
                                class="required-entry _required select admin__control-select">
                            <?php if ($countries) : ?>
                                <?php foreach ($countries as $_country) : ?>
                                    <option
                                        value="<?= $block->escapeHtmlAttr($_country["value"]); ?>" <?= $_country["value"] == $seller["country_id"] ? 'selected="selected"' : ''; ?>><?= $block->escapeHtml($_country["label"]); ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>
                <div class="admin__field field field-region_id required _required">
                    <label class="admin__field-label"  id="region-unavailable">
                        <span><?= $block->escapeHtml(__('State/Province')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select id="seller_region_id_id" name="region_id"
                                title="<?= $block->escapeHtmlAttr(__("State/Province")); ?>"
                                class="select admin__control-select" style="display:none;">
                            <option value=""><?= $block->escapeHtml(__('Please select')); ?></option>
                        </select>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?= $block->escapeHtml(__('State/Province')) ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" id="seller_region" name="region" class="admin__control-text"
                               value="<?= $block->escapeHtmlAttr($seller['region']) ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?= $block->escapeHtml(__('Postal Code')) ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="postcode" class="admin__control-text"
                               value="<?= $block->escapeHtmlAttr($seller['postcode']) ?>"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?= $block->escapeHtml(__('City')) ?>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="city" class="admin__control-text"
                               value="<?= $block->escapeHtmlAttr($seller['city']) ?>"/>
                    </div>
                </div>
                <div class="admin__field required _required">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Contact Number')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" pattern="\(?\+?(\d{1,4})?\)?\(?\d{3,4}\)?[\s.-]?\d{3,4}[\s.-]?(\d{3,6})?"
                               name="telephone" class="admin__control-text"
                               value="<?= $block->escapeHtmlAttr($seller['telephone']) ?>"
                               data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Website URL')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" name="website_url" class="admin__control-text"
                               value="<?= $block->escapeHtmlAttr($seller['website_url']) ?>" />
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Operating Hours')) ?></span>
                    </label>
                    <div class="admin__field-control">
                    </div>
                </div>
                <div class="admin__field required _required">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Ship To')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select multiple name="ship_to" id="ship_to" class="required-entry _required select admin__control-multiselect" style="overflow:hidden">
                            <option value="domestic" selected><?= $block->escapeHtml(__('Domestic')); ?></option>
                            <option value="international"><?= $block->escapeHtml(__('International')); ?></option>
                        </select>
                    </div>
                </div>
                <?php
                $sellerShipTo = isset($seller['ship_to']) ? $seller['ship_to'] : null;
                ?>
                <div class="admin__field required _required" id="ship_to_country_field" <?= $sellerShipTo && in_array('international', $sellerShipTo) ? '' : 'style="display:none"' ?>>
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Ship To Country')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select id="ship_to_country" name="ship_to_country" class="_required select admin__control-multiselect" multiple>
                            <?php if ($shipToCountries) : ?>
                                <?php foreach ($shipToCountries as $index => $_country) : ?>
                                    <?php
                                    $sellerShipToCountry = $seller["ship_to_country"] ? explode(",", $seller["ship_to_country"]) : null;
                                    ?>
                                    <option
                                        value="<?= $block->escapeHtmlAttr($_country["value"]); ?>" <?= $sellerShipToCountry && in_array($_country["value"], $sellerShipToCountry) ? 'selected' : ''; ?>><?= $block->escapeHtml($_country["label"]); ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label">
                        <?= $block->escapeHtml(__('Term & Conditions')) ?>
                    </label>
                    <div class="admin__field-control">
                        <textarea rows="7" id="term_and_conditions" type="text" name="term_and_conditions"
                                  class="admin__control-text"
                                  value=""><?= $helper->filter($seller['term_and_conditions']); ?></textarea>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>

    <div class="fieldset-wrapper admin__collapsible-block-wrapper">
        <div class="fieldset-wrapper-title" data-toggle="collapse" data-target="#operaing_hours_fieldset">
            <strong class="admin__collapsible-title">
                <?= $block->escapeHtml(__('Operating Hours')) ?>
            </strong>
        </div>
        <div id="operaing_hours_fieldset" class="admin__fieldset-wrapper-content admin__collapsible-content">
            <fieldset class="admin__fieldset">
                <script>
                    require([
                        'jquery',
                        'mdtimepicker'
                    ], function ($) {
                        $(document).on("focus", "input[name*='_time']", function () {
                            // $(this).attr('readOnly', false);
                            // $(this).timepicker({
                            //     'timeFormat': 'hh:mm tt',
                            //     'ampm': true,
                            //     'disableTextInput': true
                            // });
                            console.log($(this))
                            $(this).mdtimepicker({
                                readOnly: true
                            })

                            return false;
                        });
                        
                        $('[data-fieldname="operating_hours_status"]').on('change', function() {
                            changeOperatingHoursStatus($(this).val(), $(this).data('fieldcode'));
                        });

                        $('[name="remove_operating_hours"]').on('click', function() {
                            removeOperatingHoursStatus($(this).data('fieldcode'), $(this).data('count'));
                        });

                        $('[name="add_operating_hours"]').on('click', function() {
                            var fieldcode = $(this).data('fieldcode');
                            var count = parseInt($('#' + fieldcode + '_time_count').val()) + 1;
                            
                            var newTimeField = $('#operating-hours-template').clone(true);
                            $(newTimeField).attr("id", fieldcode + '_' + count + '_operating_hours')
                            .show()
                            .find("input, span")
                            .each(function () {
                                var id = $(this).attr('id');
                                var name = $(this).attr('name');
                                var fieldName = $(this).data('fieldcode');

                                if (fieldName == "opening_time" || fieldName == "closing_time") {
                                    $(this).attr("name", "operating_hours[" + fieldcode + "][" + count + "][" + fieldName + "]");
                                }

                                if (name == "remove_operating_hours") {
                                    $(this).attr("data-count", count);
                                    $(this).attr("data-fieldcode", fieldcode);
                                }
                            });

                            $('#' + fieldcode + '_time_container').append(newTimeField);
                            $('#' + fieldcode + '_time_count').val(count);
                        });

                        function removeOperatingHoursStatus(fieldcode, count) 
                        {
                            $('#' + fieldcode + '_' + count + '_operating_hours').remove();
                        }

                        function changeOperatingHoursStatus(val, fieldcode) 
                        {
                            if (val && val == "open") {
                                $('#' + fieldcode + '_operating_hours_container').show();
                                // $('#' + fieldcode + '_operating_hours_container').find('input').each(function() {
                                //     $(this).attr('data-validate', '{required:true}');
                                // });
                            } else {
                                $('#' + fieldcode + '_operating_hours_container').hide();
                            }
                        }
                    });
                </script>
                <?php foreach ($block->getDayNames() as $day): ?>
                    <?php
                    $fieldPrefix = $day['code'];
                    ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml($day['label']) ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select data-fieldcode="<?= $fieldPrefix ?>" data-fieldname="operating_hours_status" name="operating_hours[<?= $fieldPrefix ?>][status]" class="_required select admin__control-select">
                                <?php foreach ($block->getOperatingStatusList() as $status): ?>
                                    <option value="<?= $status['value'] ?>"><?= $status['label'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="admin__field-control" id="<?= $fieldPrefix ?>_operating_hours_container" style="display:none">
                            <div id="<?= $fieldPrefix ?>_time_container">
                                <div id="<?= $fieldPrefix ?>_0_operating_hours">
                                    <table style="width: 70%">
                                        <tr>
                                            <td style="padding-right: 15px">
                                                <div class="admin__field">
                                                    <label class="admin__field-label">
                                                        <span><?= __('Opening Hours') ?></span>
                                                    </label>
                                                    <div class="admin__field-control">
                                                        <input class="admin__control-text" type="text" autocomplete="off" value="" name="operating_hours[<?= $day['code'] ?>][0][opening_time]">
                                                    </div>
                                                </div>
                                            </td>
                                            <td style="padding-right: 15px">
                                                <div class="admin__field">
                                                    <label class="admin__field-label">
                                                        <span><?= __('Closing Hours') ?></span>
                                                    </label>
                                                    <div class="admin__field-control">
                                                        <input class="admin__control-text" type="text" autocomplete="off" value="" name="operating_hours[<?= $day['code'] ?>][0][closing_time]">
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div>
                                                    <span data-count="0" data-fieldcode="<?= $fieldPrefix ?>" name="remove_operating_hours">
                                                        <i class="fa fa-trash" style="font-size: 20px;padding-top: 25px;"></i>
                                                    </span>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <br />
                            <input type="hidden" id="<?= $fieldPrefix ?>_time_count" value="0" />
                            <button type="button" name="add_operating_hours" data-fieldcode="<?= $fieldPrefix ?>">
                                <span><?= $block->escapeHtml(__("Add More Time")); ?></span>
                            </button>
                        </div>
                    </fieldset>
                    <br />
                <?php endforeach; ?>
            </fieldset>
            <div id="operating-hours-template" style="display:none">
                <table style="width: 70%">
                    <tr>
                        <td style="padding-right: 15px">
                            <div class="admin__field">
                                <label class="admin__field-label">
                                    <span><?= __('Opening Hours') ?></span>
                                </label>
                                <div class="admin__field-control">
                                    <input class="admin__control-text" type="text" autocomplete="off" value="" fieldcode="opening_time">
                                </div>
                            </div>
                        </td>
                        <td style="padding-right: 15px">
                            <div class="admin__field">
                                <label class="admin__field-label">
                                    <span><?= __('Closing Hours') ?></span>
                                </label>
                                <div class="admin__field-control">
                                    <input class="admin__control-text" type="text" autocomplete="off" value="" fieldcode="closing_time">
                                </div>
                            </div>
                        </td>
                        <td>
                            <div>
                                <span name="remove_operating_hours">
                                    <i class="fa fa-trash" style="font-size: 20px;padding-top: 25px;"></i>
                                </span>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="fieldset-wrapper admin__collapsible-block-wrapper">
        <div class="fieldset-wrapper-title" data-toggle="collapse" data-target="#images">
            <strong class="admin__collapsible-title">
                <?= $block->escapeHtml(__('Images')) ?>
            </strong>
        </div>
        <div id="images" class="admin__fieldset-wrapper-content admin__collapsible-content">
            <fieldset class="admin__fieldset">
                <fieldset class="admin__field">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Banner')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <div class="image image-placeholder">
                            <div class="uploader">
                                <div class="fileinput-button form-buttons button">
                                    <input type="file" id="image" name="image"
                                           title="<?= $block->escapeHtmlAttr(__('Banner')) ?>"
                                           onchange="document.getElementById('banner_preview').src = window.URL.createObjectURL(this.files[0])"/>
                                </div>
                            </div>
                            <div class="product-image-wrapper">
                                <p class="image-placeholder-text">
                                    <?= $block->escapeHtml(__('Browse to find or drag image here(Size 1240x400)')) ?>
                                </p>
                            </div>
                        </div>
                        <?php if ($seller['image']): ?>
                            <div class="image">
                                <img src="<?= $block->escapeUrl($helper->getMediaUrl() . $seller['image']) ?>"
                                     title="<?= $block->escapeHtmlAttr($seller['image']) ?>"
                                     alt="<?= $block->escapeHtmlAttr($seller['image']) ?>" width="150"
                                     class="small-image-preview v-middle"
                                     id="banner_preview"
                                     data-ui-id="adminhtml-seller-edit-tab-main-0-fieldset-element-file-thumbnail">
                            </div>
                        <?php else: ?>
                            <div class="image">
                                <img src="<?= $block->escapeUrl($placeHolderImageSrc) ?>"
                                     width="150"
                                     class="small-image-preview v-middle no-image"
                                     id="banner_preview"
                                     data-ui-id="adminhtml-seller-edit-tab-main-0-fieldset-element-file-thumbnail">
                            </div>
                        <?php endif; ?>
                    </div>
                </fieldset>
                <fieldset class="admin__field">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Logo')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <div class="image image-placeholder">
                            <div class="uploader">
                                <div class="fileinput-button form-buttons button">
                                    <input type="file" id="thumbnail" name="thumbnail"
                                           title="<?= $block->escapeHtmlAttr(__('Logo')) ?>"
                                           onchange="document.getElementById('logo_preview').src = window.URL.createObjectURL(this.files[0])"/>
                                </div>
                            </div>
                            <div class="product-image-wrapper">
                                <p class="image-placeholder-text">
                                    <?= $block->escapeHtml(__('Browse to find or drag image here(Size 200x200)')) ?>
                                </p>
                            </div>
                        </div>
                        <?php if ($seller['thumbnail']): ?>
                            <div class="image">
                                <img src="<?= $block->escapeUrl($helper->getMediaUrl() . $seller['thumbnail']) ?>"
                                     title="<?= $block->escapeHtmlAttr($seller['thumbnail']) ?>"
                                     alt="<?= $block->escapeHtmlAttr($seller['thumbnail']) ?>" width="150"
                                     class="small-image-preview v-middle"
                                     id="logo_preview"
                                     data-ui-id="adminhtml-seller-edit-tab-main-0-fieldset-element-file-thumbnail">
                            </div>
                        <?php else: ?>
                            <div class="image">
                                <img src="<?= $block->escapeUrl($placeHolderImageSrc) ?>"
                                     width="150"
                                     class="small-image-preview v-middle no-image"
                                     id="logo_preview"
                                     data-ui-id="adminhtml-seller-edit-tab-main-0-fieldset-element-file-thumbnail">
                            </div>
                        <?php endif; ?>
                    </div>
                </fieldset>
            </fieldset>
        </div>
    </div>
    <div class="fieldset-wrapper admin__collapsible-block-wrapper">
        <div class="fieldset-wrapper-title" data-toggle="collapse" data-target="#social">
            <strong class="admin__collapsible-title">
                <?= $block->escapeHtml(__('Social Information')) ?>
            </strong>
        </div>
        <div id="social" class="admin__fieldset-wrapper-content admin__collapsible-content">
            <fieldset class="admin__fieldset">
                <?php if ($helper->isAllowedSocial('twitter')): ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Twitter')) ?></span>
                            <input type="checkbox" name="tw_active"
                                   value="<?= $seller['tw_active']; ?>" <?= ($seller['tw_active'] == 1) ? 'checked' : '' ?>
                                   style="margin: 5px;">
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="twitter_id" id="twitter_id" class="admin__control-text"
                                   title="Twitter" value="<?= $block->escapeHtmlAttr($seller['twitter_id']) ?>">
                            <p><?= __('Please enter a full URL. Ex: https://www.twitter.com/page') ?></p>
                        </div>
                    </fieldset>
                <?php endif; ?>
                <?php if ($helper->isAllowedSocial('facebook')): ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Facebook')) ?></span>
                            <input type="checkbox" name="fb_active" <?= ($seller['fb_active'] == 1) ? 'checked ' : '' ?>
                                   value="<?= $block->escapeHtmlAttr($seller['fb_active']) ?>" style="margin: 5px;">
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="facebook_id" id="facebook_id" class="admin__control-text"
                                   title="Facebook" value="<?= $block->escapeHtmlAttr($seller['facebook_id']) ?>">
                            <p><?= __('Please enter a full URL. Ex: https://www.facebook.com/page') ?></p>
                        </div>
                    </fieldset>
                <?php endif; ?>
                <?php if ($helper->isAllowedSocial('instagram')): ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Instagram')) ?></span>
                            <input type="checkbox"
                                   name="instagram_active" <?= ($seller['instagram_active'] == 1) ? 'checked ' : '' ?>
                                   value="<?= $seller['instagram_active']; ?>" style="margin: 5px;">
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="instagram_id" id="instagram_id" class="admin__control-text"
                                   title="Instagram" value="<?= $block->escapeHtmlAttr($seller['instagram_id']) ?>">
                            <p><?= __('Please enter a full URL. Ex: https://www.instagram.com/page') ?></p>
                        </div>
                    </fieldset>
                <?php endif; ?>
                <?php if ($helper->isAllowedSocial('google')): ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Google Plus')) ?></span>
                            <input type="checkbox"
                                   name="gplus_active" <?= ($seller['gplus_active'] == 1) ? 'checked ' : '' ?>
                                   value="<?= $block->escapeHtmlAttr($seller['gplus_active']) ?>" style="margin: 5px;">
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="gplus_id" id="gplus_id" class="admin__control-text"
                                   title="Google Plus" value="<?= $block->escapeHtmlAttr($seller['gplus_id']) ?>">
                            <p><?= __('Please enter a full URL. Ex: https://plus.google.com/page') ?></p>
                        </div>
                    </fieldset>
                <?php endif; ?>
                <?php if ($helper->isAllowedSocial('youtube')): ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Youtube')) ?></span>
                            <input type="checkbox"
                                   name="youtube_active" <?= ($seller['youtube_active'] == 1) ? 'checked ' : '' ?>
                                   value="<?= $block->escapeHtmlAttr($seller['youtube_active']) ?>" style="margin: 5px;">
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="youtube_id" id="youtube_id" class="admin__control-text"
                                   title="Youtube" value="<?= $block->escapeHtmlAttr($seller['youtube_id']) ?>">
                            <p><?= __('Please enter a full URL. Ex: https://www.youtube.com/page') ?></p>
                        </div>
                    </fieldset>
                <?php endif; ?>
                <?php if ($helper->isAllowedSocial('linkedin')): ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Linkedin')) ?></span>
                            <input type="checkbox"
                                   name="linkedin_active" <?= ($seller['linkedin_active'] == 1) ? 'checked ' : '' ?>
                                   value="<?= $block->escapeHtmlAttr($seller['linkedin_active']) ?>" style="margin: 5px;">
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="linkedin_id" id="linkedin_id" class="admin__control-text"
                                   title="Linkedin" value="<?= $block->escapeHtmlAttr($seller['linkedin_id']) ?>">
                            <p><?= __('Please enter a full URL. Ex: https://www.linkedin.com/page') ?></p>
                        </div>
                    </fieldset>
                <?php endif; ?>
                <?php if ($helper->isAllowedSocial('vimeo')): ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Vimeo')) ?></span>
                            <input type="checkbox"
                                   name="vimeo_active" <?= ($seller['vimeo_active'] == 1) ? 'checked ' : '' ?>
                                   value="<?= $block->escapeHtmlAttr($seller['vimeo_active']) ?>" style="margin: 5px;">
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="vimeo_id" id="vimeo_id" class="admin__control-text" title="Vimeo"
                                   value="<?= $block->escapeHtmlAttr($seller['vimeo_id']) ?>">
                            <p><?= __('Please enter a full URL. Ex: https://www.vimeo.com/page') ?></p>
                        </div>
                    </fieldset>
                <?php endif; ?>
                <?php if ($helper->isAllowedSocial('printerest')): ?>
                    <fieldset class="admin__field">
                        <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Printerest')) ?></span>
                            <input type="checkbox"
                                   name="pinterest_active" <?= ($seller['pinterest_active'] == 1) ? 'checked ' : '' ?>
                                   value="<?= $block->escapeHtmlAttr($seller['pinterest_active']) ?>" style="margin: 5px;">
                        </label>
                        <div class="admin__field-control">
                            <input type="text" name="pinterest_id" id="pinterest_id" class="admin__control-text"
                                   title="Printerest" value="<?= $block->escapeHtmlAttr($seller['pinterest_id']) ?>">
                            <p><?= __('Please enter a full URL. Ex: https://www.printerest.com/page') ?></p>
                        </div>
                    </fieldset>
                <?php endif; ?>
            </fieldset>
        </div>
    </div>
    <?= $block->getChildHtml('additional_fields'); ?>
</form>
<script>
    require(["jquery"], function ($) {
        $('#ship_to').on('change', function() {
            changeShipTo($(this).val());
        });

        function changeShipTo(val) 
        {
            if (val && val.length) {
                if (val.includes("international")) {
                    $('#ship_to_country').addClass('required-entry');
                    $('#ship_to_country_field').show();
                } else {
                    $('#ship_to_country').removeClass('required-entry');
                    $('#ship_to_country_field').hide();
                }
            } else {
                $('#ship_to_country').removeClass('required-entry');
                $('#ship_to_country_field').hide();
            }
        }
    });
</script>
<script>
    require(["jquery", "prototype", "mage/adminhtml/form"], function ($) {
        var old_region_name = $("#seller_region").val();
        var seller_region_id = "<?= isset($seller["region_id"]) ? (int)$seller["region_id"] : 0;?>"
        $("seller_region_id_id").setAttribute("defaultValue", seller_region_id);
        new regionUpdater("seller_country_id", "seller_region_id", "seller_region_id_id", <?= $_directoryHelper->getRegionJson();?>);
        if (!$("#seller_region_id_id:visible").length) {
            $("#region-unavailable").hide();
        } else {
            $("#region-unavailable").show();
        }
        $("#seller_country_id").on("change", function () {
            if (!$("#seller_region_id_id:visible").length) {
                $("#region-unavailable").hide();
            } else {
                $("#region-unavailable").show();
            }
        })
        $("#seller_region_id_id").on("change", function () {
            if ($(this).val() && $("#seller_region").length > 0) {
                $("#seller_region").val($("#seller_region_id_id option:selected").text());
            } else if ($("#seller_region").length > 0) {
                $("#seller_region").val(old_region_name);
            }
        })
    })
</script>
<script type="text/javascript">
    require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function ($) {
        $(document).ready(function () {
            $('input[type="checkbox"]').each(function () {
                $(this).bind('change', function () {
                    if ($(this).prop('checked')) {
                        $(this).val(1);
                    } else {
                        $(this).val(0);
                    }
                });
            });
            $(window).on("load resize", function (e) {
                console.log($(window).width());
                if ($(window).width() >= 768) {
                    wysiwygcompany_description = new wysiwygSetup("company_description", {
                        "width": "99%",  // defined width of editor
                        "height": "200px", // height of editor
                        "plugins": [{"name": "image"}], // for image
                        "tinymce": {
                            "toolbar": "formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap",
                            "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                        }
                    });
                    wysiwygcompany_description.setup("exact");

                    wysiwygcompany_description = new wysiwygSetup("return_policy", {
                        "width": "99%",  // defined width of editor
                        "height": "200px", // height of editor
                        "plugins": [{"name": "image"}], // for image
                        "tinymce": {
                            "toolbar": "formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap",
                            "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                        }
                    });
                    wysiwygcompany_description.setup("exact");

                    wysiwygcompany_description = new wysiwygSetup("shipping_policy", {
                        "width": "99%",  // defined width of editor
                        "height": "200px", // height of editor
                        "plugins": [{"name": "image"}], // for image
                        "tinymce": {
                            "toolbar": "formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap",
                            "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                        }
                    });
                    wysiwygcompany_description.setup("exact");

                }
            });
        });
    });
</script>
